### ISSUE TITLE
Any variation without borders?

### ISSUE THREAD

**Issue by awesomepandata** [mmolch/mmolch-xfce#1]
![border](https://user-images.githubusercontent.com/61336668/94631387-b8982880-029e-11eb-85d2-f85af5c69800.png)

This theme is awesome, but in xfce, borders are not good to me. Any variation or help to remove the border?

**Comment by mmolch** [comment]
Personally I like this a lot more than having no borders. It gives good contrast when having windows of the same color on top of each other (like a terminal in fullscreen in the back and a another terminal window in front) and the borders can be properly grabbed with the mouse for resizing. This also is in line with client-side decorated windows in this theme. So, at least I won't create a borderless version. (It shouldn't really take a lot of time to crop the images from the theme in gimp to remove the borders though)
